name: my_news_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  cached_network_image: ^3.0.0
  google_fonts: ^2.1.0
  rxdart: ^0.27.1
  http: ^0.13.3
  intl: ^0.17.0
  equatable: ^2.0.2
  flutter_bloc: ^7.0.1
  url_launcher: 6.0.4 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
